### ISSUE TITLE
Global styles get added in the wrong order when using styled-components

### ISSUE THREAD

**Issue by gligoran** [ben-rogerson/twin.macro#277] opened 2020-12-26 13:47 UTC
Hi,

I'm trying to upgrade a project to Tailwind v2 that also uses TailwindUI.

I'm using react with styled-components.

I'm running into problems with `@tailwindcss/forms` that renders my input fields differently depending wether I declare them in the same file as my App component or in a separate file. It seems like the order in the generated `style` element is not the same.

I've built an example here: https://github.com/gligoran/twin-react-styled-components-bug (couldn't make it work on codesandbox: https://codesandbox.io/s/twin-react-styled-components-bug-bg82n).

The main part of the problem is this difference in order as you can see from these 2 screenshots:

![image](https://user-images.githubusercontent.com/444829/103152208-f3b6d480-4785-11eb-9c37-f9934fe5d592.png)

![image](https://user-images.githubusercontent.com/444829/103152214-0c26ef00-4786-11eb-99c6-3de19fd76b98.png)

**Comment by ben-rogerson** [comment] 2020-12-27 02:42
Thanks for the bug demo on this.

Recently in our Discord server, Anark described a similar issue within a custom webpack setup.
The style order is described as being correct on the initial load but switches the ordering shortly after that.

> In case anyone else ever runs into this, I fixed it by moving GlobalStyles into its own stateless CSSReset component and importing CSSReset and adding it to app.jsx instead of GlobalStyles
> 
> ```js
> // CSSReset.js
> import { GlobalStyles } from 'twin.macro'
> 
> export default function CSSReset() {
>   return <GlobalStyles />
> }
> ```

Could you perhaps try a similar solution here and report back?

If that fixes it I'm unsure how I could fix this aside adding a note within the documentation as this is handled by `styled-components`.

**Comment by gligoran** [comment] 2021-01-02 08:52
Hey @ben-rogerson.

Yes, that solves it for me as well. Is this considered a permanent or a temporary solution?

Oh, thanks for the great plugin/macro 👍

**Comment by ben-rogerson** [comment] 2021-01-03 22:21
For the react examples I recommend adding GlobalStyles in the `index.js` file:

```js
// index.js
import React from 'react'
import { render } from 'react-dom'

import { GlobalStyles } from 'twin.macro'
import App from './App'

render(
  <>
    <GlobalStyles />
    <App />
  </>,
  document.getElementById('root'),
)
``` 

This also fixes the issue mentioned above but also avoids a new file having to be added.

**Comment by gligoran** [comment] 2021-01-04 07:53
That was one of the first things I've tried when I came across this issue.

But with this solution even `App.js` in my example is an external component relative to where `GlobalStyles` are used, so even the `Works` section of the screenshot I've mentioned is not broken.

I've made a [PR in my example repo](https://github.com/gligoran/twin-react-styled-components-bug/pull/2) where you can see the change and hooked it up to Vercel so you can see it live: https://twin-react-styled-components-bug-j2rvmq7nv.vercel.app/

**Comment by ben-rogerson** [comment] 2021-01-04 10:08
Yeah damn, you're right! I was a little too hasty to close this.

I'm beginning to think it's an issue with styled-components rather than twin.
I tested with the raw global import and the problem still remains:

```js
import { createGlobalStyle } from 'styled-components'
const GlobalStyles = createGlobalStyle`...`

render(
  <>
    <GlobalStyles />
    <App />
  </>,
  document.getElementById('root'),
)
```

I'll do some more digging 👍

**Comment by ben-rogerson** [comment] 2021-01-04 21:48
Looks like there is an [existing issue with styled-components with the ordering of the global styles](https://github.com/styled-components/styled-components/issues/3146).
This issue only popped up now because of the recent move to supply all base styles via the GlobalStyles import (rather than an external `base.min.css` file / unsupported `addBase` in plugins).

The workaround is to export `<GlobalStyles />` from an external component:

```js
// GlobalStyles.js
import React from 'react'
import { GlobalStyles } from 'twin.macro'

export default function GlobalStylesComponent() {
  return <GlobalStyles />
}
```

```js
// index.js
import React from 'react'
import { render } from 'react-dom'
import App from './App'

import GlobalStyles from './GlobalStyles'

render(
  <>
    <GlobalStyles />
    <App />
  </>,
  document.getElementById('root'),
)
```

**Comment by gligoran** [comment] 2021-01-06 06:39
@ben-rogerson thanks for you explanation. I'll follow that issue in the `styled-components/styled-components` for more update. Hopefully it gets fixed soon.

**Comment by aclement-ikarusdev** [comment] 2021-01-10 22:34
I am wondering if it's actually an issue with styled-components. I am having the exact same issue but with emotion/styled.

**Comment by ben-rogerson** [comment] 2021-01-11 04:28
> I am wondering if it's actually an issue with styled-components. I am having the exact same issue but with emotion/styled.

I haven't noticed this myself, would you be able to show me a minimum bug reproduction either on CodeSandbox or a repo?

**Comment by aclement-ikarusdev** [comment] 2021-01-11 15:04
@ben-rogerson So apparently it wasn't emotion itself but the issue is with storybook, I made a fork of your example repo at: https://github.com/aclement-ikarusdev/twin.examples/tree/master/storybook-emotion

**Comment by ben-rogerson** [comment] 2021-01-13 01:24
> @ben-rogerson So apparently it wasn't emotion itself but the issue is with storybook, I made a fork of your example repo at: https://github.com/aclement-ikarusdev/twin.examples/tree/master/storybook-emotion

Thanks for pushing that example through - I've fixed the issue by [adding a cache that specifies it's prepended to the head](https://github.com/ben-rogerson/twin.examples/commit/14ed140bb99b9bfb9b99d5112c9dd6432dd17aba).

**Comment by mcgrathg** [comment] 2021-02-13 06:07
> > I am wondering if it's actually an issue with styled-components. I am having the exact same issue but with emotion/styled.
> 
> I haven't noticed this myself, would you be able to show me a minimum bug reproduction either on CodeSandbox or a repo?

@ben-rogerson I'm seeing this issue with NextJS and Emotion.

The base styles from preflight are overriding the input styles from `@tailwindcss/forms`.

I forked the [Next Emotion example](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion) to add the forms plugin here: https://codesandbox.io/s/relaxed-sound-xb4t6.

The text inputs are using the reset style from preflight, instead of the form plugin's styling that has a little bit of padding.

![image](https://user-images.githubusercontent.com/5464892/107843249-8e4f8f00-6d97-11eb-9da4-15d0eb612464.png)

**Comment by mcgrathg** [comment] 2021-02-13 19:51
Using your [CSSReset fix from above](https://github.com/ben-rogerson/twin.macro/issues/277#issuecomment-751418515) seems to have fixed this for NextJS & Emotion.

https://codesandbox.io/s/twinmacro-example-with-tailwindforms-global-component-workaround-ke6ud

**Comment by ben-rogerson** [comment] 2021-02-14 03:20
Interesting - I've hear a couple of similar stories lately with emotion so I think I'll make this the preferred approach.

**Comment by ethanve** [comment] 2021-02-15 23:20
I'm actually experiencing this _with_ a custom `GlobalStyles` component and `@tailwindcss/forms`. Doesn't seem to propagate correctly

**Comment by ben-rogerson** [comment] 2021-02-16 23:19
@ethanve If you could post a repo up, I could take a look into it further

**Comment by ethanve** [comment] 2021-02-17 20:02
> @ethanve If you could post a repo up, I could take a look into it further

Here you go -- thank you! I'm sure it's something on my end.

 https://github.com/ethanve/twin-macro-cra-styled-form-bug

**Comment by ethanve** [comment] 2021-02-17 21:06
@ben-rogerson missed a commit. Just pushed!

**Comment by anthify** [comment] 2021-03-12 18:32
I'm having the same issue where @tailwind/forms is being overridden by the global styles. The workaround doesn't work for me, and I'm using it with Next.js and styled-components.

**Comment by ben-rogerson** [comment] 2021-03-23 22:38
@ethanve @anthify I've taken a look into the issue with styled-components + twin and found that styled-components is not preserving the global styles ordering. There are a few issues on the topic already ([Issue](https://github.com/styled-components/styled-components/issues/3146) / [Issue](https://github.com/styled-components/styled-components/issues/3321) / [Issue](https://github.com/styled-components/styled-components/issues/3293)) and [I've added to one of them](https://github.com/styled-components/styled-components/issues/3146#issuecomment-754229239) at the start of 2021 and haven't noticed action on any of them.

The unfortunate reality is that the styled-components project isn't being maintained anymore.
There has been a lack of updates/fixes by the [single remaining maintainer](https://github.com/styled-components/styled-components/graphs/contributors) - probablyup - who looks to have stopped committing to github (almost completely) since the end of January 2021 ([profile](https://github.com/probablyup)).
I'm worried about the future of styled-components and lack of updates/fixes coming through.
There are [too many critical issues](https://github.com/styled-components/styled-components/issues) and nothing is being discussed by maintainers or acted upon.
It's a shame given [how many developers are still enjoying the project](https://2020.stateofcss.com/en-US/technologies/css-in-js/#styled_components) but I cannot recommend anyone to start a new project with styled-components until we start seeing releases again.

**Comment by ethanve** [comment] 2021-03-24 22:03
@ben-rogerson thank you for the detailed response! What _would_ you recommend using to start a new project then?

**Comment by stenowtf** [comment] 2021-03-25 08:48
I was having the same problem on global styles ordering with a new CRA + styled-components and I "solved" it by switching to emotion. Bummer.

**Comment by ben-rogerson** [comment] 2021-03-27 23:56
> @ben-rogerson thank you for the detailed response! What _would_ you recommend using to start a new project then?

Emotion, goober or stitches. All of these libraries have the ability to maintain the ordering of global styles.

**Closed** 2021-07-03 02:00 UTC

**Comment by AaronFeledy** [comment] 2021-08-03 01:02
I was running into this issue and none of the above fixed it for me. Ultimately, I discovered that in my `.babelrc`, I had the `@emotion/babel-plugin-jsx-pragmatic` plugin configured with `"module": "@emotion/core"` which was a remnant from an older version of Emotion. Emotion 11 should be using `"module": "@emotion/react"`. Once I changed the `core` to `react`, it started working as expected.

**Comment by Shaker-Hamdi** [comment] 2022-05-15 18:09
Any updates on that issue?

**Comment by timstarkk** [comment] 2022-09-22 17:20
Our team had this issue today using @emotion/react and storybook. 
The styles were only ordered incorrectly while viewing components in storybook, the issue was not affecting the actual application.

we fixed by moving `<GlobalStyles />` to be called after` <Story />` like shown below:
![Screen Shot 2022-09-22 at 12 19 38 PM](https://user-images.githubusercontent.com/20097098/191811296-968e6be6-a45c-4455-86cf-9adb04923dad.png)

**Comment by koniuszy** [comment] 2022-12-06 12:32
@ben-rogerson I've migrated to emotion a few days ago and this Issue (including [the solution](https://github.com/ben-rogerson/twin.macro/issues/277#issuecomment-754240911)) was crucial, it should stayed pinned in my opinion, unless there is another solution I am not aware of?

**Comment by ben-rogerson** [comment] 2022-12-06 19:38
Fair call 👍

**Comment by mtedao** [comment] 2023-05-03 07:20
I have same issue when created app with Vite and the fix doesn't work for me
<img width="606" alt="image" src="https://user-images.githubusercontent.com/104081563/235853743-8c489e7e-8976-45a7-a660-ac08975aff17.png">

**Comment by shepherdjerred** [comment] 2023-07-01 19:11
I'm running into this issue using the [Vite react styled-components typescript template](https://github.com/ben-rogerson/twin.examples/tree/master/vite-styled-components-typescript). It looked similar to [this issue](https://github.com/ben-rogerson/twin.macro/issues/773) -- the reset was causing my buttons not to have a background color.

Sorry, I don't have an example, but I have a fix for anyone else who is running into this issue.

1. Remove all references to `GlobalStyles` from `twin.macro`.
2. Create an `index.css` which has the following contents:
    ```
    @tailwind base;
    ```
3. Import `index.css` in your `main.tsx` file.

This fixed the issue for me. I'm looking forward to a more proper fix in the future!

**Comment by SanskarDahiya** [comment] 2025-04-28 09:58
I've migrated to emotion a few days ago and this Issue still persist

**Comment by SanskarDahiya** [comment] 2025-04-28 10:41
Hi There,
Hi @ben-rogerson 

I am facing a small issue while preparing for the migration to Next.js 15 App Router.
Earlier, using **twin.macro + emotion**, the MainContainer was correctly applying **flex-1** for mobile and **flex-2** for desktop devices.

Now, after moving to styled-components (Not any specific reason, just nextjs support styled-component for now), due to the CSS ordering between styled-components and twin.macro, flex-1 is being applied even on desktop.

Has you faced this before? Would appreciate any guidance or workaround suggestions to fix it.
Thanks a lot in advance!


![Image](https://github.com/user-attachments/assets/d9fe845a-e3ff-4665-932f-6a7353a83878)
