### ISSUE TITLE
The same custom media query + Tailwind media query don't merge correctly

### ISSUE THREAD

**Issue by joneslloyd** [ben-rogerson/twin.macro#379] opened 2021-04-06 11:31 UTC
If I use something like this:
```
const BodyStyles = styled('div')(({ layout = false, imageUrl = false }) => [
    tw`flex flex-col bg-transparent divide-y divide-widget-white-line`,
    ('full' === layout && imageUrl) && {
        ...tw`lg:(bg-no-repeat bg-x183y-36 bg-x100y100)`,
        [`@media (min-width: ${theme('screens.lg')})`]: {
            'background-image': `radial-gradient(circle at 61% 153px, ${theme('colors.widget-purple.light-65')}, ${theme('colors.widget-purple.light')} 30%), url('${imageUrl}')`,
        },
    },
]);
```

...where I'm blending custom Tailwind classes `bg-x183y-36` and `bg-x100y100` (via theme > extend > backgroundPosition and theme > extend > backgroundSize respectively) and custom CSS (`background-image`), I'm finding that only the last property/properties are applied to the component.

So in this above example, only the `background-image` is applied. If I swap the order so that the `...tw``lg:(bg-no-repeat bg-x183y-36 bg-x100y100)``,` line is the last one in the object, then only the custom Tailwind classes in that line are applied (and the `background-image` is ignored).

Is this a bug or expected behaviour?

For anybody else running into this issue, a hack/fix is to use the CSS properties directly (not via Tailwind classes) as I originally did [here](https://github.com/ben-rogerson/twin.macro/discussions/378).

**Comment by ben-rogerson** [comment] 2021-04-08 22:08
Hey Lloyd, thanks for posting this issue.

There's a definite bug here - the custom media query isn't merging correctly with the tailwind media query.

Here's a minimum test case:

```js
const Test = styled('div')(() => [
  {
    ...tw`lg:text-white`, // This doesn't get merged into the media query underneath
    [`@media (min-width: ${theme('screens.lg')})`]: { // This media query trumps the tailwind media query
      background: 'red',
    },
  },
])
```

The workaround is to move your tailwind classes _inside_ the custom media query:

```js
const BodyStyles = styled('div')(({ layout = false, imageUrl = false }) => [
    tw`flex flex-col bg-transparent divide-y divide-widget-white-line`,
    ('full' === layout && imageUrl) && {
        [`@media (min-width: ${theme('screens.lg')})`]: {
			...tw`bg-no-repeat bg-x183y-36 bg-x100y100`,
            'background-image': `radial-gradient(circle at 61% 153px, ${theme('colors.widget-purple.light-65')}, ${theme('colors.widget-purple.light')} 30%), url('${imageUrl}')`,
        },
    },
]);
```

I'll take a look into this and release a patch.

**Comment by joneslloyd** [comment] 2021-04-09 09:28
Thank you! And thanks for the workaround snippet too 🙂

**Comment by ben-rogerson** [comment] 2021-04-24 08:26
I've taken another look at this but I haven't arrived at a solution.

Here's the code twin delivers to the css-in-js library:

```js
const Test = _styled("div")({ ...{
    "@media (min-width: 1024px)": {
      "--tw-text-opacity": "1",
      color: "rgba(255, 255, 255, var(--tw-text-opacity))"
    }
  },
  // This doesn't get merged into the media query underneath
  [`@media (min-width: ${"1024px"})`]: {
    // This media query trumps the tailwind media query
    background: "red"
  }
});
```

The issue is, that the

**Comment by ben-rogerson** [comment] 2021-06-08 22:48
With the new [screen import](https://github.com/ben-rogerson/twin.macro/pull/408), we'll be able to merge styles correctly like this:

```js
import tw, { screen } from 'twin.macro'

const Test = styled('div')({
    ...tw`lg:text-white`,
    [screen`lg`]: { background: 'red' },
  },
)

// or

const Test = styled('div')({
    ...tw`lg:text-white`,
    ...screen`lg`({ background: 'red' }),
  },
)
```

The screen import will be released soon 👍

**Closed by ben-rogerson** 2021-06-08 22:48 UTC
