### ISSUE TITLE
Dark mode modifier bug when creating customized styled components

### ISSUE THREAD

**Issue by lucasfontesgaspareto** [ben-rogerson/twin.macro#740] opened 2022-09-09 01:06 UTC
This code looks perfect

  ```ts
  export const SidebarItem = styled(Link)<SidebarItemProps>(({ exact }) => {
    return [
      tw`flex items-center p-2 text-base font-normal rounded-lg text-zinc-900 dark:text-white hover:bg-zinc-100 dark:hover:bg-zinc-700`,
      exact && tw`bg-zinc-700`
    ]
  })
  ```
As you can see
![image](https://user-images.githubusercontent.com/8084651/189250098-670698b8-3454-4b7f-9938-e566b00464cf.png)

But when i use `dark:` modifier  a bug happens as seen in the image below

  ```ts
  export const SidebarItem = styled(Link)<SidebarItemProps>(({ exact }) => {
    return [
      tw`flex items-center p-2 text-base font-normal rounded-lg text-zinc-900 dark:text-white hover:bg-zinc-100 dark:hover:bg-zinc-700`,
      exact && tw`dark:bg-zinc-700`
    ]
  })
  ```
  
![image](https://user-images.githubusercontent.com/8084651/189250142-90d29ed3-5d11-47bc-8778-a5fe9a60acc6.png)

it doesn't make much sense to me because as I have a condition in the case where the exacts are false, I shouldn't even load the css classes into the component

For now my solution is ```exact && tw`bg-zinc-500 bg-opacity-20` ```  but this is clearly a bug right?

My versions:
"tailwindcss": "^3.1.8"
"twin.macro": "^3.0.0-rc.3"

**Comment by ben-rogerson** [comment] 2022-09-09 23:17
Are you using styled components?
This sounds like [the dark mode pinned issue](https://github.com/ben-rogerson/twin.macro/issues/310) - could you please confirm?

**Comment by lucasfontesgaspareto** [comment] 2022-09-10 18:40
> 

Exactly the same

**Comment by ben-rogerson** [comment] 2022-09-11 01:53
Thanks for reporting back but nothing I can do from my end I'm afraid.
Closing this issue as it's a duplicate of #310

**Closed by ben-rogerson** 2022-09-11 01:53 UTC
