### ISSUE TITLE
@tailwindcss/typography nextjs emotion css error

### ISSUE THREAD

**Issue by cs50victor** [ben-rogerson/twin.macro#640] opened 2022-03-11 08:57 UTC
I ran into this issue when I tried using the @tailwindcss/typography plugin with mdx-bundler to create a blog post. 

I'm making use of nextjs + twin.macro(emotion) + mdx-bundler.

The typography classes are being mixed up 

```css
<style data-emotion="css l2qb0n-ArticleContainer">
              .css-l2qb0n-ArticleContainer {
                display: block;
                max-width: 65ch;
                font-family: Radial, SF Pro Text, -apple-system, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
                --tw-prose-body: #3f3f46;
               .........
                font-size: 1rem;
                line-height: 1.75;
                color: var(--tw-prose-body);

                :where(ul ul {
                    margin-top:0.75em; margin-bottom:0.75em;
                  }

                  :where(blockquote p:last-of-type):not(:where([class~="not-prose"] *))::after {
                    content:close-quote;
                  }

                  :where(blockquote p:first-of-type):not(:where([class~="not-prose"] *))::before {
                    content:open-quote;
                  }

                  @media (prefers-color-scheme: dark) {
                    --tw-prose-body:var(--tw-prose-invert-body); --tw-prose-headings:var(--tw-prose-invert-headings); --tw-prose-lead:var(--tw-prose-invert-lead); --tw-prose-links:var(--tw-prose-invert-links); --tw-prose-bold:var(--tw-prose-invert-bold); --tw-prose-counters:var(--tw-prose-invert-counters); --tw-prose-bullets:var(--tw-prose-invert-bullets); --tw-prose-hr:var(--tw-prose-invert-hr); --tw-prose-quotes:var(--tw-prose-invert-quotes); --tw-prose-quote-borders:var(--tw-prose-invert-quote-borders); --tw-prose-captions:var(--tw-prose-invert-captions); --tw-prose-code:var(--tw-prose-invert-code); --tw-prose-pre-code:var(--tw-prose-invert-pre-code); --tw-prose-pre-bg:var(--tw-prose-invert-pre-bg); --tw-prose-th-borders:var(--tw-prose-invert-th-borders); --tw-prose-td-borders:var(--tw-prose-invert-td-borders);
                  }

                  margin-left:auto; margin-right:auto; padding-left:1.5rem; padding-right:1.5rem; margin-top:1rem; margin-bottom:1rem; label:ArticleContainer;
                }

                ;
              }
```

I've tried everything, from downgrading both package versions to adding postcss as a dependency, but nothing fixed the issue. Has anyone else faced this problem? @ben-rogerson

**Comment by lukesmurray** [comment] 2022-03-20 19:59
Also ran into this issue. Seems like the output CSS is mangled. maybe missing right brackets.

**Comment by lukesmurray** [comment] 2022-03-20 21:05
I don't think this is caused by MDX bundler. The issue appears even for raw html pages in the nextjs emotion example.

**Comment by ben-rogerson** [comment] 2022-03-20 21:45
I'm working on support for the latest version of the typography plugin. Have you tried rolling it back a few versions?

**Comment by cs50victor** [comment] 2022-03-20 21:50
> I'm working on support for the latest version of the typography plugin. Have you tried rolling it back a few versions?

I was able to make the prose className work by using it in the className (not in tw=""), but I had to roll it back to version 0.5.0, and include ----- import "@tailwindcss/typography/dist/typography.min.css" - at the top of my file

**Comment by cs50victor** [comment] 2022-03-20 22:02
but it's purely CSS, and the dark mode doesn't work

**Comment by lukesmurray** [comment] 2022-03-20 22:12
@ben-rogerson version `0.4.1` works. Makes sense since `0.5.0` is only compatible with tailwind v3+ and not compatible with tailwind v2. Unfortunately @cs50victor v0.5.0 also adds support for dark mode so you may need to rely on the css override for a bit if you need dark mode. If you don't need dark mode downgrading typography to 0.4.1 should work.

Thanks for all the hard work @ben-rogerson. twin remains one of my favorite tools for projects <3!

**Comment by lukesmurray** [comment] 2022-03-20 22:13
@ben-rogerson might be helpful if you pin the typography dependency in package.json?

https://github.com/ben-rogerson/twin.macro/blob/5e7e2122f75d4536d714a4e6d1088770e985f2c4/package.json#L79

Not sure if it matters but I know I looked there for a pin and assumed something was broken when 0.5 didn't work for me.

**Comment by jjrchrds** [comment] 2022-05-12 01:46
just found this, not sure if I filed the same issue, but 0.5.1 and 0.4.1 aren't working at all for me.

**Comment by ben-rogerson** [comment] 2022-05-15 00:26
Closing this issue in favor of #686

**Closed by ben-rogerson** 2022-05-15 00:26 UTC
