### ISSUE TITLE
Add installation for Next.js

### ISSUE THREAD

**Issue by theairbend3r** [ben-rogerson/twin.macro#16] opened 2020-03-23 10:17 UTC
Hi Ben!

Amazing work!

Could you please add installation for Next.js? [Here's](https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss-emotion) an example setup for next+tailwind+emotion setup on Next's Github page.

As an aside; in the `create-react-app + emotion` installation, I saw the following - 
```
// In your App.js or index.js entry
// (tailwindcss is pre-installed with twin.macro)
```

What is `tailwindcss` here? Is it a `.css` file which contains the following?
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```

One last question; If I have installed Next.js + tailwindcss as shown on tailwindcss' [Github repo](https://github.com/tailwindcss/setup-examples/tree/master/examples/nextjs), then how would I go about installing twin.macro?

**Comment by ben-rogerson** [comment] 2020-03-23 10:49
> Could you please add installation for Next.js? [Here's](https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss-emotion) an example setup for next+tailwind+emotion setup on Next's Github page.

That zeit example needs to be updated. 
I was waiting for a request on this, I'll add examples for emotion + styled-components 👍 

> What is `tailwindcss` here? Is it a `.css` file which contains the following?

It's the official Tailwind repo which is a dependency of Twin. 
It's so you can import their "browser reset" file. The equivalent "non-js" way of adding it is: `@import "tailwindcss/base";`.

> One last question; If I have installed Next.js + tailwindcss as shown on tailwindcss' [Github repo](https://github.com/tailwindcss/setup-examples/tree/master/examples/nextjs), then how would I go about installing twin.macro?
 
Perhaps a Codesandbox example will help here. I'll let you know when it's up.

**Comment by theairbend3r** [comment] 2020-03-23 11:03
Awesome! Thanks for the super quick reply! 

I saw ` "Complete dev functions (production mode only at the moment)"` in the Roadmap on the README.md page. Does it mean the it won't work properly when I do `npm run dev`?

Also, about the last question (_Adding twin.macro+emotion to an existing installation of Next+tailwindcss_). Could explain in brief about how it would work? I am a little confused about how Tailwind, PostCSS, styled-components (emotion) work in dev/production setting. Just a simple flow of what happens when I'll run my app in dev vs prod. Or maybe point me to resource (blog/article) which explains it well. I could not find any good material on this online.

_Sorry if the questions are too basic, I'm a JS noob and have recently started learning JS and React._

**Comment by Djiit** [comment] 2020-03-24 10:58
Hey guys, I'm playing with Next.js and Emotion too, but I cant get the tw attribute to work... Is there any additional step ?

**Comment by ben-rogerson** [comment] 2020-03-24 22:44
@theairbend3r Here's a brand new [Next + Tailwind  + Emotion Starter](https://codesandbox.io/s/next-tailwind-emotion-starter-8h2b2) to help out. 

>I saw "Complete dev functions (production mode only at the moment)" in the Roadmap on the README.md page. Does it mean the it won't work properly when I do npm run dev?

I've [updated README.md to be more descriptive](https://github.com/ben-rogerson/twin.macro/commit/fc3237a891a2536eec3c3ca1499b06dfb7c14309#diff-04c6e90faac2675aa89e2176d2eec7d8R695). You can use `npm run dev` and it will work fine.

When you run styled-components in dev, you'll notice more information about which element the style is defined upon. Try inspecting the source code after running your app in dev vs prod.

@Djiit Check the [Next + Tailwind  + Emotion Starter](https://codesandbox.io/s/next-tailwind-emotion-starter-8h2b2) - the fix is to add the '@emotion/babel-preset-css-prop' package. Unfortunately [the css prop doesn't work without it](https://github.com/emotion-js/emotion/issues/1237#issuecomment-514842909).

**Comment by theairbend3r** [comment] 2020-03-25 02:18
I just check out the codesandbox, it look amazing @ben-rogerson!

> When you run styled-components in dev, you'll notice more information about which element the style is defined upon. Try inspecting the source code after running your app in dev vs prod.
Thanks for the suggestion, I'll check out the source code in dev vs prod.

Yesterday, I came across this [blogpost](https://dev.to/brendanrc2/how-we-use-tailwind-in-components-f77) which uses tailwind to build components. In the blog post they demonstrate the following - 

```
# Define Button component
const Button = (props) => 
  <button {...props} className="px-4 py-2 bg-gray-700 text-white" />

# Use button component
<Button>Save Form</Button>
```

or with more customizations like - 
```
# Define the component
const DEFAULT = "border border-solid border-transparent";

const COLORS = {
  green: "text-white bg-green-400 hover:bg-green-500",
  red: "text-white bg-red-400 hover:bg-red-500"
};

const Button = ({ color, children, className, ...props }) => {
  className = [className, DEFAULT, COLORS[color]].join(" ");

  return (
    <button {...props} className={className}>
      {children}
    </button>
  );
};



# Use the component
<Button color="red" className="mb-2"/>
```


If we use emotion.js, we can directly create a component using `styled.button` as opposed to passing the `{...props}` like in the above code. Is my understanding correct?

What advantage does using emotion.js have in this case? (`Tailwind + Twin + Emotion + Next` vs `Tailwind + Next`) 


One last thing, how do I get that setup running? I think you haven't updated the README.md with the steps yet. 

Thanks again for making this library! :)

**Comment by ben-rogerson** [comment] 2020-03-25 02:56
>If we use emotion.js, we can directly create a component using styled.button as opposed to passing the {...props} like in the above code. Is my understanding correct?

Yes, you're correct. I find it much easier to create elements with Emotion/Styled components.

>What advantage does using emotion.js have in this case? (Tailwind + Twin + Emotion + Next vs Tailwind + Next)

Vanilla Tailwind creates all the css ahead of it's usage in your project from the `tailwind.config.js` file. This means that you'll need to strip out all the unused css with a tool like purgeCss to bring the filesize back down. By using a Twin, you'll only add the css that you use.
I enjoy using Emotion + Twin for the ease of creating new elements, conditional styling, composing styles and scoping my css to the component.
Perhaps have a read of [this article](https://medium.com/dailyjs/what-is-actually-css-in-js-f2f529a2757) for a little more info.

>One last thing, how do I get that setup running? I think you haven't updated the README.md with the steps yet.

I've just updated the Readme with the instructions. But you might have an easier time just downloading the zip from the [codesandbox starter](https://codesandbox.io/s/next-tailwind-emotion-starter-hufz3) and moving any of your code into that.

![image](https://user-images.githubusercontent.com/21288568/77496778-ac6c8200-6e9b-11ea-9d5f-fd88a06c6722.png)

**Comment by theairbend3r** [comment] 2020-03-25 07:22
Thanks for the speedy help @ben-rogerson! Appreciate it!

One final thing, how do we normalize the vendor prefixes? Earlier, I think postcss was doing that (autoprefixer). In this setup, how would we do that?

**Comment by Djiit** [comment] 2020-03-26 10:16
Allright I can confirm it works ! Thanks !

Also tested : since Next.JS 9.2, you don't need next-css anymore ! Even simpler setup!

**Comment by ben-rogerson** [comment] 2020-03-29 04:34
@theairbend3r 

>How does twin.macro know that we're using this defaultConfig.stub.js without even installing it?

[Twin imports `tailwindcss/stubs/defaultConfig.stub`](https://github.com/ben-rogerson/twin.macro/blob/master/src/tailwindHelpers.js#L3) from the official `tailwindcss` package.

>Why do we only keep the theme: {...}? Why not Variants: {...}, or Plugins:{...} or the rest of the objects?

Twin uses the same code as Tailwind to combine the default stub with your own config. But there's not too much more shared code between the two packages. All variants for all classes are already available in Twin 🙌 and the other config items - except plugins - just aren't used.

>In the codesandbox you linked above, you've used a theme.js file which uses {themeprovider} from emotion.js. Why is that? I installed this setup from the instructions in the README.md and tailwindcss functionality works for me without the theme.js file.

In the codesandbox, I'm aiming to demonstrate how you can reuse values from your `tailwind.config.js` in your app with a theme provider.
Here's the code in the starters that I hoped would demonstrate the theme provider functionality:  

```js
// components/Button.js
const StyledButton = styled.button(
  ({ theme }) => [
    css`
      color: ${theme.colors.white};
    `
  ]
)
```

It can be really useful, for example, grabbing your custom screen sizes and passing them to a javascript function without the need for ` tw`` `.

> Also tested : since Next.JS 9.2, you don't need next-css anymore ! Even simpler setup!

@Djiit I see they added support for css but wasn't able to get it working. I receive `You may need an appropriate loader to handle this file type.` when next-css is removed. If you could point out the fix on the [twin next starter](https://codesandbox.io/s/next-tailwind-emotion-starter-8h2b2), it would be much appreciated :)

**Comment by ben-rogerson** [comment] 2020-03-29 04:38
I've added the new next.js examples to the readme so I'll close this for now.

If you have any questions about how Twin works, please create a new issue.
Try to keep on topic with the issue title as it'll help others find better-targeted advice in the future - cheers!

**Closed by ben-rogerson** 2020-03-29 04:38 UTC
Labels: usage example request
