### ISSUE TITLE
extended colors (in object format) including a default color name gets replaced with the default colors value

### ISSUE THREAD

**Issue by trkaplan** [ben-rogerson/twin.macro#104] opened 2020-07-07 13:54 UTC
in tailwind.config.js if you define a color, with a name including a default colors name **in object format**, gets the value of the default color. 
ie.
`module.exports = {
  theme: {
    extend: {
      colors: {
        'my-blue': {
          100: '#2200ff'
        }
      }
    }
  }
}
`
There is a class `blue-100` in tailwind default color palette. So when you use `my-blue-100` twin.macro uses that color value instead of the one defined in this config. 
That looks like a regex issue I think. It happens in text-color, bg-color or border-color.

Here is the sample forked from the starter.
https://codesandbox.io/s/next-emotion-tailwind-twin-starter-tf34f?file=/tailwind.config.js

Thanks @regenrek for giving point to when color definition is an object not a string.

**Comment by ben-rogerson** [comment] 2020-07-09 21:50
Thanks for the bug report, I'm looking into it 👍

**Comment by ajitid** [comment] 2020-07-19 04:14
Also functionality of picking up colors from `extend` of config seems to be broken. Either it doesn't picks up colors from `extend` at all or if it is able to recognize one of the defined color, as issue author said, reverts to an inbuilt one.

**Comment by ajitid** [comment] 2020-07-19 04:23
For me `extend`'s functionality for colors is completely broken, even if I define colors in plain string format. Either it does not identifies the color, or like author said, reverts to an inbuilt one.

**Comment by ben-rogerson** [comment] 2020-07-19 04:42
@ajitid could you please post your config that demonstrates the bug?
I'm finishing up with some features on the next release and then I'm tackling this bug.

**Comment by ajitid** [comment] 2020-07-19 04:56
```js
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        colors: {
          yellow: "#ee1", // isn't identified
          brand: {
            "gray-300": "#ee1ee1", // inbuilt one gets applied
          },
        },
      },
    },
  },
};
```

---

Packages:

```
"twin.macro": "^1.5.0",
"@emotion/core": "^10.0.28",
"@emotion/styled": "^10.0.27",
"next": "9.4.4",
```

**Comment by ajitid** [comment] 2020-07-19 05:06
Oh sorry, I think I didn't restarted dev server so updated config wasn't picked up. Passing plain string does work, its what OP posted which isn't working.

**Comment by ben-rogerson** [comment] 2020-07-19 22:27
This match bug was fixed in 1.5.1 🎉 

Feel free to reopen the issue if there's any issues.

**Closed by ben-rogerson** 2020-07-19 22:27 UTC
Labels: bug

**Comment by avinash-BB** [comment] 2020-09-11 06:55
Seeing this issue again with v1.8.3
Sample tailwind config which reproduces the issue:
`module.exports = { theme: { extend: { colors: { 'my-green': { 100: '#F1F8E6' } } } } }
`
Then using 'bg-my-green-100' doesn't apply '#F1F8E6', instead it applies tailwind's default green-100 color which is '#F0FFF4'.

**Comment by ben-rogerson** [comment] 2020-09-14 11:33
@avinash-BB I couldn’t see any issues using custom colors, [check out this demo here](https://codesandbox.io/s/issue-demonstraton-for-104-02wx7?file=/src/App.js)
