### ISSUE TITLE
Remove text color from error output

### ISSUE THREAD

**Issue by lightyen** [ben-rogerson/twin.macro#591] opened 2021-12-13 09:25 UTC
Is there an option that I can remove ANSI escape code?

![image](https://user-images.githubusercontent.com/28860476/145785382-c159b4c0-8077-44d1-b63f-2bb52a738f06.png)

**Comment by ben-rogerson** [comment] 2021-12-15 21:43
Hey there,
There's no option on this, but looks like a bug I'd need to fix.
What's your `tailwind.config.js` that generates this bad output?

**Comment by lightyen** [comment] 2021-12-16 01:00
@ben-rogerson my tailwind config is nothing:
```js
module.exports = {}
```

**Comment by ben-rogerson** [comment] 2021-12-16 02:03
Interesting, must be from recent tailwindcss updates. I'll aim to to provide a patch fix shortly.

**Comment by RootAndroid58** [comment] 2021-12-16 13:45
tailwind v3 update is yet to come u need to wait till then 
the cyan color scheme is in v3 
check #588

Duplicate of #589

**Comment by ben-rogerson** [comment] 2021-12-16 19:41
@RootAndroid58 I believe this issue is more about the poor output rather than the missing cyan color here.

**Comment by ben-rogerson** [comment] 2022-01-12 21:50
@lightyen Twin uses [chalk](https://github.com/chalk/chalk) for the terminal colors - I'll update the package in the next version, hopefully that may fix this output.

**Comment by lightyen** [comment] 2022-05-11 09:31
I found that `ansi-html` doesn't support 24-bit color format, something like: `\x1b[38;5;0;0;0mhelloworld\x1b[0m`.

Then I have made a package to fix that:
![image](https://user-images.githubusercontent.com/28860476/167817848-8b4e562a-40c0-46ec-b343-d2f71651ac7a.png)

**Comment by ben-rogerson** [comment] 2022-05-11 10:12
Sounds interesting!
Would you be providing a PR I could take a look at?

**Comment by lightyen** [comment] 2022-05-11 10:57
@ben-rogerson https://github.com/lightyen/react-refresh-webpack-plugin

**Comment by ben-rogerson** [comment] 2022-05-14 07:39
So in that example you fixed the display of the error overlay, that's always been an issue - nice one 👍 

I'm wondering how we can bring this fix into some of the twin examples. 
How could we use `ansi-html-string` to fix the overlay on [react-emotion-typescript](https://github.com/ben-rogerson/twin.examples/tree/master/webpack-emotion-typescript)?

**Comment by ben-rogerson** [comment] 2022-05-30 22:39
Closing due to inactivity - feel free to reopen if there's something to act on here

**Closed by ben-rogerson** 2022-05-30 22:39 UTC
