### ISSUE TITLE
Can't resolve 'fs' , 'module' w/{Gatsby + Styled-Components}

### ISSUE THREAD

**Issue by kelvindecosta** [ben-rogerson/twin.macro#327] opened 2021-02-09 07:50 UTC
## Overview

Hey!

I've been using `twin.macro` with my Gatsby site for quite some time now.
I ran into a bug a few weeks back which I was able to temporarily rectify.
I still think the underlying problem is not solved.

## Reproduction

Please refer to [this sandbox](https://codesandbox.io/s/cant-resolve-fs-module-wgatsby-styled-components-fiujk).

The following steps were taken to create this reproduction:

- I cloned the starter repository with Gatsby and Styled-Components setup.
- I made changes to the `src/` folder to minimize the reproduction.

    <details>
    <summary>File Structure</summary>

  ```
  src
  ├── components
  │   ├── layout.js
  └── pages
      ├── 404.js
      └── index.js
  ```

    </details>

    <details>
    <summary>

  `src/components/layout.js`

    </summary>

  ```jsx
  import React from 'react'
  import tw, { GlobalStyles } from 'twin.macro'

  const LayoutWrapper = tw.div`bg-red-500`

  const Layout = ({ children }) => (
    <LayoutWrapper>
      <GlobalStyles />
      {children}
    </LayoutWrapper>
  )

  export default Layout
  ```

    </details>

    <details>
    <summary>

  `src/pages/index.js`

    </summary>

  ```jsx
  import React from 'react'
  import Layout from '../components/layout'

  const App = () => <Layout>Hello</Layout>

  export default App
  ```

    </details>

## Behavior

<details>
<summary>Errors</summary>

```
error Generating development JavaScript bundle failed
  Can't resolve 'fs' in '/sandbox/node_modules/babel-plugin-styled-components/lib/visitors' (2 times)
  Can't resolve 'fs' in '/sandbox/node_modules/cosmiconfig/dist' (2 times)
  Can't resolve 'fs' in '/sandbox/node_modules/path-type' (2 times)
  Can't resolve 'fs' in '/sandbox/node_modules/resolve-from' (2 times)
  Can't resolve 'fs' in '/sandbox/node_modules/resolve/lib' (4 times)
  Can't resolve 'module' in '/sandbox/node_modules/resolve-from' (2 times)
```

</details>

#### Changes

Back when I first encountered this, I looked for similar issues and stumbled upon [this one](https://github.com/ben-rogerson/twin.examples/issues/20).
I followed the [fix](https://github.com/ben-rogerson/twin.examples/blob/master/next-styled-components/next.config.js#L5), by modifying the Webpack configuration.

<details>
<summary>

`gatsby-node.js`

</summary>

```js
exports.onCreateWebpackConfig = ({ actions }) => {
  // Fixes packages that depend on fs/module module
  actions.setWebpackConfig({
    node: {
      fs: 'empty',
      module: 'empty',
    },
  })
}
```

</details>

#### Errors

<details>
<summary>Terminal</summary>

```
  warn Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
  warn Critical dependency: the request of a dependency is an expression
```

</details>

<details>
<summary>Browser (Visiting http://localhost:8000)</summary>

```
  Uncaught TypeError: styled_components_macro__WEBPACK_IMPORTED_MODULE_1__.default.div is not a function
```

</details>

#### Changes

I resorted to the following changes, which seem to have gotten rid of the errors.
Ideally, I would prefer not to do this.

<details>
<summary>

`src/components/layout.js`

</summary>

```diff
import React from 'react'
+ import styled from 'styled-components'
import tw, { GlobalStyles } from 'twin.macro'

- const LayoutWrapper = tw.div`bg-red-500`
+ const LayoutWrapper = styled.div`
+  ${tw`bg-red-500`}
+ `
```

</details>

#### Errors

I think this bug has a more elegant solution.
This is because it still seems to be affecting other pieces of code.
For example, using the macro in `.mdx` files

<details>
<summary>Problem with MDX files</summary>

```mdx
<!-- src/pages/index.mdx -->

import tw from 'twin.macro'

export const Red = tw.div`text-red-500`

<Red>Hello</Red>
```

```
  WebpackError: ReferenceError: tw is not defined
```

</details>

## Comment

Any help with this issue will be greatly appreciated!

Thank you!

**Comment by ben-rogerson** [comment] 2021-02-10 05:47
Thanks for the great bug writeup and example - much appreciated.

I found that the example I've made works fine until I try using the same Layout component you've added which I thought was really strange.

Anyway, the errors hint that babel-plugin-macros isn't being loaded properly so I added a custom .babelrc according to the gatsby docs which fixes the errors without having to modify your webpack config:

```js
// .babelrc
{
  "plugins": ["babel-plugin-macros"],
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ]
  ]
}
``` 

I'm not sure what the root cause of this is yet - it's a little puzzling.
I tested the output of twins <GlobalStyles /> alongside the styled-components imports that are swapped in and it worked fine 🤷‍♂️

**Comment by kelvindecosta** [comment] 2021-02-10 08:23
Thank you for the detailed response!
I will follow your approach and create a `.babelrc` file.

I forgot to mention something very interesting.

I [modified the original reproduction](https://codesandbox.io/s/cant-resolve-fs-module-wgatsby-styled-components-fiujk):

- <details>
    <summary>File Structure</summary>

  ```
  src
  ├── components
  │   ├── layout.js
  │   ├── styles.js
  └── pages
      ├── 404.js
      └── index.js
  ```

    </details>

- <details>
    <summary>

  `src/components/styles.js`

    </summary>

  ```jsx
  import React from "react"
  import { GlobalStyles } from "twin.macro"

  const Styles = () => <GlobalStyles />

  export default Styles
  ```

    </details>

- <details>
    <summary>

  `src/components/layout.js`

    </summary>

  ```jsx
  import React from "react"
  import tw from "twin.macro"

  import Styles from "./styles"

  const LayoutWrapper = tw.div`bg-red-500`

  const Layout = ({ children }) => (
    <LayoutWrapper>
      <Styles />
      {children}
    </LayoutWrapper>
  )

  export default Layout
  ```

    </details>

- <details>
    <summary>

  `src/pages/index.js`

    </summary>

  ```jsx
  import React from "react"
  import Layout from "../components/layout"

  const App = () => <Layout>Hello</Layout>

  export default App
  ```

    </details>

**The errors no longer appear!**

I suspect this has something to do with how the `tw` macro is **imported alongside named exports** from `"twin.macro"`.

Thanks again!

**Comment by kelvindecosta** [comment] 2021-02-10 08:45
This is very interesting...
After adding the `.babelrc` configuration in your comment, I was able to completely rectify the bug!

I was having another unrelated issue with `.mdx` files
Updates were not triggering hot reload.
After adding `.babelrc`, the browser's console no longer displays "App is updated", but rather throws warnings that a full reload is required.

I had no Babel configuration initially.
I think you're right about the it being changed elsewhere.
Maybe there is something wrong with Gatsby's defaults?

**Comment by kelvindecosta** [comment] 2021-03-07 05:59
Hey @ben-rogerson 

I tried adding `babel-plugin-twin` to my Gatsby site.
I used the `.babelrc` configuration in your comment, and prepended `babel-plugin-twin` before `babel-plugin-macros`.
I get the following error message:

```
Uncaught ReferenceError: tw is not defined
```

I did a little research and I think Gatsby expands `babel-plugin-macros` after it extracts queries.
This could mean that the `tw` macro is not available until some steps are completed.
Maybe this is why the babel config seems to get changed?

**Comment by ben-rogerson** [comment] 2021-03-07 21:45
I'll have a closer look into this - there could be a bug with babel-plugin-twin + gatsby here

**Comment by ajmalafif** [comment] 2021-04-11 07:15
hey @kelvindecosta did you solve the issue you have with `.mdx` file or is that still going on? Curious how did you solve because I am on Gatsby + emotion (but not TS) and `twin.macro` works everywhere but `.mdx` file.

**Comment by kelvindecosta** [comment] 2021-04-11 16:05
Hey @ajmalafif 

Unfortunately the issue with `.mdx` files still persists.

I'm not sure whether it's an issue with `twin.macro` or `mdx`.
The `gatsby-plugin-mdx` plugin has/had a few issues with import resolution.

I'll update you if the issue gets resolved!

**Comment by ajmalafif** [comment] 2021-04-14 03:44
@kelvindecosta i stumbled upon this:
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/?=mdx#shouldblocknodefromtransformation

Not sure how to use it, but could this be a potential solution to use `twin.macro` in `.mdx`?

**Comment by mihaildu** [comment] 2021-04-22 14:53
Hey guys, I ran into a similar issue when using `GlobalStyles` in the same way described above. It seems that `babel-plugin-macros` relies on older version of webpack (< 5) to polyfill some packages when running in the browser (such as `fs` or `path`). However, gatsby is using [webpack version 5](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L159) which doesn't polyfill them anymore.

The errors I was getting are similar to
```
failed Re-building development bundle - 0.503s
ERROR in ./node_modules/babel-plugin-macros/dist/index.js 9:10-25
Module not found: Error: Can't resolve 'path' in '.../node_modules/babel-plugin-macros/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

My solution was to include the global styles in `gatsby-browser.js`
```
// gatsby-browser.js
import "tailwindcss/dist/base.min.css"
```

This would work and get rid of the errors. I tried the `.babelrc` described above and it works as well!

**Comment by ajmalafif** [comment] 2021-04-22 16:19
@mihaildu hey thanks for sharing. Curious if your setup is for TypeScript or including `.babelrc` just works for your setup?

**Comment by mihaildu** [comment] 2021-04-22 16:42
I'm using plain JavaScript and yes, just adding the `.babelrc` works for me.

**Comment by mihaildu** [comment] 2021-04-23 12:51
One last thing, I noticed `GlobalStyles` works too, but only if applied in [gatsby-browser.js](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/) file, if using the wrapPageElement export like so
```
// gatsby-browser.js
import React from 'react';
import { GlobalStyles } from 'twin.macro';
...
export const wrapPageElement = ({ element, props }) => (
  <>
    <GlobalStyles />
    <Layout {...props}>{element}</Layout>
  </>
);
```

**Comment by ben-rogerson** [comment] 2021-07-03 02:04
Closing for now, feel free to reopen if there's still an issue here.

**Closed by ben-rogerson** 2021-07-03 02:04 UTC
