### ISSUE TITLE
Styled component function syntax not applying styles in correct order

### ISSUE THREAD

**Issue by tannerlinsley** [ben-rogerson/twin.macro#297] opened 2021-01-18 18:46 UTC
The bug is best visible in this codesandbox reproduction: https://codesandbox.io/s/hungry-curran-m2zvw?file=/src/App.js.

Expectation: Only the "active" tab should be white in dark mode
Actual: All of the tabs are white in dark mode.

**Comment by tannerlinsley** [comment] 2021-01-18 18:47
Another note I forgot is that *seems* to only happen in dark mode, but there could be deeper issues afoot in light mode that I'm just not sussing out.

**Comment by ben-rogerson** [comment] 2021-01-20 10:15
Thanks for the great bug reproduction.

This issue looks like it's [the `&`bug introduced in styled-components@5.2](https://github.com/styled-components/styled-components/issues/3334#issuecomment-738488350).

I can only think of these workarounds right now: 

- Use css variables for theming - you can see an [advanced approach here](https://github.com/ben-rogerson/twin.macro/blob/master/docs/advanced-theming.md)
  The idea is to set the css vars in `:root` or `body`  (using the globalStyles import from styled-components), then set colors in tailwind that use those variables (eg: `colors: { "primary": "var(--color-primary)" }`). You can then toggle the global variable with js to change the theme. 
- Drop back a version 5.1.1 in `styled-components` - [here's your working demo](https://codesandbox.io/s/styled-components-works-in-511-2cgtg)
- Or switch to emotion - It doesn't have the & issues styled-components has right now.

**Comment by ben-rogerson** [comment] 2021-01-30 21:28
Closing this as this has been covered in #277 
If dropping back to styled-components 5.1 didn't solve this, feel free to re-open 👍

**Closed by ben-rogerson** 2021-01-30 21:28 UTC
